#!/usr/bin/env bash
# gen-cks-config.sh — generate the cks runtime config + env file from the CURRENT
# checkout locations. No hand-edited absolute paths: everything is resolved at
# run time, so moving the repos just means re-running this script.
#
# Emits (into the cks repo root):
#   cks-stablenet.yaml   absolute-path cks config (ckg + ckv + domain wiring)
#   cks.env              shell exports the coding-agent plugin's .mcp.json needs
#                        (CKS_MCP_BIN / CKS_CONFIG / GO_STABLENET_ROOT / CKV_OLLAMA_ENDPOINT)
#
# Usage:
#   ./scripts/gen-cks-config.sh
#   GO_STABLENET_ROOT=/path ./scripts/gen-cks-config.sh   # override source tree
#
# Then either `source cks.env` in your shell, or add one line to ~/.zshrc:
#   source /abs/path/to/code-knowledge-system/cks.env
set -euo pipefail

abs() { ( cd "$1" 2>/dev/null && pwd ) || { echo "ERROR: path not found: $1" >&2; exit 1; }; }

CKS_ROOT="$(abs "$(dirname "${BASH_SOURCE[0]}")/..")"
CKG_REPO="$(abs "${CKG_REPO:-$CKS_ROOT/../code-knowledge-graph}")"
CKV_REPO="$(abs "${CKV_REPO:-$CKS_ROOT/../code-knowledge-vector}")"
GSN="$(abs "${GO_STABLENET_ROOT:-$CKS_ROOT/../go-stablenet}")"
OLLAMA_URL="${CKV_OLLAMA_ENDPOINT:-http://localhost:11434}"
EMBED_MODEL="${EMBED_MODEL:-bge-m3}"

CKS_MCP_BIN="$CKS_ROOT/bin/cks-mcp"
CKG_BIN="$CKG_REPO/bin/ckg"
CKV_BIN="$CKV_REPO/bin/ckv"
CONFIG="$CKS_ROOT/cks-stablenet.yaml"
ENVFILE="$CKS_ROOT/cks.env"

# ---- cks-stablenet.yaml (absolute paths, resolved now) --------------------
cat > "$CONFIG" <<YAML
# GENERATED by scripts/gen-cks-config.sh — do not hand-edit; re-run to refresh.
version: 1

backends:
  ckg:
    path: "$CKS_ROOT/data/ckg-stablenet/graph.db"
    source_root: "$GSN"
    binary_path: "$CKG_BIN"
    policy_file: "$CKS_ROOT/generated/policies/stablenet-ckg-policy.yaml"
    timeout_ms: 5000
  ckv:
    path: "$CKS_ROOT/ckv-stablenet"
    timeout_ms: 3000
    embed_model: "$EMBED_MODEL"
    ollama_url: "$OLLAMA_URL"
    binary_path: "$CKV_BIN"

listen:
  http_addr: "127.0.0.1:8080"
  mcp_stdio: true

logging:
  level: "info"
  mode: "prod"
  footprint_dir: "$CKS_ROOT/logs/footprint"
  audit_dir: "$CKS_ROOT/logs/audit"

sanitize:
  rules_path: "$CKS_ROOT/policies/sanitization_rules.yaml"
  default_action: "drop"
  fail_closed_on_unknown_rule: true

domain:
  project_dir: "$CKS_ROOT/docs/domain-knowledge/projects/go-stablenet"
  corpus_dir: "$CKS_ROOT/generated/domain-corpus/go-stablenet"

vocab:
  glossary_path: "$CKS_ROOT/docs/domain-knowledge/projects/go-stablenet/glossary.yaml"
YAML

# ---- cks.env (exports consumed by coding-agent plugin/.mcp.json) ----------
cat > "$ENVFILE" <<ENV
# GENERATED by scripts/gen-cks-config.sh — source this from your shell profile.
# coding-agent/plugin/.mcp.json resolves \${CKS_MCP_BIN} / \${CKS_CONFIG} from here.
export CKS_MCP_BIN="$CKS_MCP_BIN"
export CKS_CONFIG="$CONFIG"
export GO_STABLENET_ROOT="$GSN"
export CKV_OLLAMA_ENDPOINT="$OLLAMA_URL"
ENV

# ---- report ---------------------------------------------------------------
echo "generated:"
echo "  $CONFIG"
echo "  $ENVFILE"
[ -x "$CKS_MCP_BIN" ] || echo "  WARN: cks-mcp not built yet ($CKS_MCP_BIN) — run 'make build-bins'"
[ -x "$CKG_BIN" ]     || echo "  WARN: ckg not built ($CKG_BIN)"
[ -x "$CKV_BIN" ]     || echo "  WARN: ckv not built ($CKV_BIN)"
echo ""
echo "activate:  source \"$ENVFILE\"     # or add that line to ~/.zshrc"
