#!/usr/bin/env bash
# gen-cks-config.sh — generate the cks runtime config + env file from the CURRENT
# checkout locations. No hand-edited absolute paths: everything is resolved at
# run time, so moving the repos just means re-running this script.
#
# Emits (into the cks repo root):
#   cks-stablenet.yaml   absolute-path cks config (ckg + ckv + domain wiring,
#                        transport: http — served by scripts/serve-cks-http.sh)
#   cks.env              shell exports the coding-agent plugin's .mcp.json needs
#                        (CKS_MCP_BIN / CKS_MCP_URL / GO_STABLENET_ROOT / CKV_OLLAMA_ENDPOINT)
#
# NOTE: the plugin's cks entry is HTTP-only ({"type":"http","url":"${CKS_MCP_URL}"});
# CKS_CONFIG is no longer emitted — nothing consumes it since the bench moved to
# the shared HTTP instance. The ip:port stays out of git: cks.env is gitignored
# and settings overrides live in ~/.claude/settings.json / .claude/settings.local.json.
#
# Usage:
#   ./scripts/gen-cks-config.sh
#   CKS_HTTP_ADDR=172.20.82.90:8080 ./scripts/gen-cks-config.sh   # LAN-reachable instance
#   CKS_DATASET_DIR=/abs/knowledge-data/pr-77-2 ./scripts/gen-cks-config.sh
#
# Then either `source cks.env` in your shell, or run scripts/apply-cc-settings.sh
# to merge the env into ~/.claude/settings.json.
set -euo pipefail

abs() { ( cd "$1" 2>/dev/null && pwd ) || { echo "ERROR: path not found: $1" >&2; exit 1; }; }

CKS_ROOT="$(abs "$(dirname "${BASH_SOURCE[0]}")/..")"
CKG_REPO="$(abs "${CKG_REPO:-$CKS_ROOT/../code-knowledge-graph}")"
CKV_REPO="$(abs "${CKV_REPO:-$CKS_ROOT/../code-knowledge-vector}")"
GSN="$(abs "${GO_STABLENET_ROOT:-$CKS_ROOT/../go-stablenet}")"
OLLAMA_URL="${CKV_OLLAMA_ENDPOINT:-http://localhost:11434}"
EMBED_MODEL="${EMBED_MODEL:-bge-m3}"

# Instance identity (echoed by cks.ops.health so callers can tell which
# instance/index they reached — see the multi-instance support in cmd/cks-mcp).
CKS_NAME="${CKS_NAME:-cks-stablenet}"
CKS_DESCRIPTION="${CKS_DESCRIPTION:-go-stablenet dataset ($EMBED_MODEL)}"

# Dataset: one directory holding graph.db (ckg) + ckv/ (vector index).
# Defaults to the canonical pr-77-2 build; override per dataset.
DATASET_DIR="$(abs "${CKS_DATASET_DIR:-$CKS_ROOT/../knowledge-data/pr-77-2}")"

# HTTP listen address. Loopback by default; set a LAN IP (e.g. 172.20.x.x:8080)
# to serve other machines — allow_remote is derived from the address.
HTTP_ADDR="${CKS_HTTP_ADDR:-127.0.0.1:8080}"
case "$HTTP_ADDR" in
  127.*|localhost*) ALLOW_REMOTE=false ;;
  *)                ALLOW_REMOTE=true ;;
esac

CKS_MCP_BIN="$CKS_ROOT/bin/cks-mcp"
CKG_BIN="$CKG_REPO/bin/ckg"
CKV_BIN="$CKV_REPO/bin/ckv"
CONFIG="$CKS_ROOT/cks-stablenet.yaml"
ENVFILE="$CKS_ROOT/cks.env"

# ---- cks-stablenet.yaml (absolute paths, resolved now) --------------------
cat > "$CONFIG" <<YAML
# GENERATED by scripts/gen-cks-config.sh — do not hand-edit; re-run to refresh.
version: 1
name: "$CKS_NAME"
description: "$CKS_DESCRIPTION"

backends:
  ckg:
    path: "$DATASET_DIR/graph.db"
    source_root: "$GSN"
    binary_path: "$CKG_BIN"
    policy_file: "$CKS_ROOT/generated/policies/stablenet-ckg-policy.yaml"
    timeout_ms: 5000
  ckv:
    path: "$DATASET_DIR/ckv"
    timeout_ms: 3000
    embed_model: "$EMBED_MODEL"
    ollama_url: "$OLLAMA_URL"
    binary_path: "$CKV_BIN"

listen:
  transport: http
  http_addr: "$HTTP_ADDR"
  allow_remote: $ALLOW_REMOTE

logging:
  level: "info"
  mode: "prod"
  footprint_dir: "$CKS_ROOT/logs/footprint"
  audit_dir: "$CKS_ROOT/logs/audit"

sanitize:
  rules_path: "$CKS_ROOT/policies/sanitization_rules.yaml"
  default_action: "drop"
  fail_closed_on_unknown_rule: true

domain:
  project_dir: "$CKS_ROOT/docs/domain-knowledge/projects/go-stablenet"
  corpus_dir: "$CKS_ROOT/generated/domain-corpus/go-stablenet"

vocab:
  glossary_path: "$CKS_ROOT/docs/domain-knowledge/projects/go-stablenet/glossary.yaml"
YAML

# ---- cks.env (exports consumed by coding-agent plugin/.mcp.json) ----------
cat > "$ENVFILE" <<ENV
# GENERATED by scripts/gen-cks-config.sh — source this from your shell profile.
# coding-agent/plugin/.mcp.json resolves \${CKS_MCP_URL} from here (http-only).
export CKS_MCP_BIN="$CKS_MCP_BIN"
export CKS_MCP_URL="http://$HTTP_ADDR/mcp"
export GO_STABLENET_ROOT="$GSN"
export CKV_OLLAMA_ENDPOINT="$OLLAMA_URL"
ENV

# ---- report ---------------------------------------------------------------
echo "generated:"
echo "  $CONFIG   (name=$CKS_NAME, dataset=$DATASET_DIR, listen=$HTTP_ADDR allow_remote=$ALLOW_REMOTE)"
echo "  $ENVFILE"
[ -x "$CKS_MCP_BIN" ] || echo "  WARN: cks-mcp not built yet ($CKS_MCP_BIN) — run 'make build-bins'"
[ -x "$CKG_BIN" ]     || echo "  WARN: ckg not built ($CKG_BIN)"
[ -x "$CKV_BIN" ]     || echo "  WARN: ckv not built ($CKV_BIN)"
[ -f "$DATASET_DIR/graph.db" ] || echo "  WARN: dataset graph.db missing ($DATASET_DIR/graph.db)"
[ -d "$DATASET_DIR/ckv" ]      || echo "  WARN: dataset ckv index missing ($DATASET_DIR/ckv)"
echo ""
echo "serve:     scripts/serve-cks-http.sh start   # on-demand HTTP instance"
echo "activate:  source \"$ENVFILE\"     # or run scripts/apply-cc-settings.sh"
